/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.antiik.hockeygamehandler.gui;

import fi.antiik.hockeygamehandler.filehandler.StandingsList;
import fi.antiik.hockeygamehandler.logic.Standings;
import java.awt.TextField;
import java.awt.event.ActionListener;
import static java.lang.Math.E;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class SelectStandings extends javax.swing.JPanel {

    /**
     * Creates new form SelectStandings
     */
    
    private StandingsList standingsList;
    private Standings standings;
    private String textField;
    public SelectStandings(Standings standings, String textField) {
        this.standings = standings;
        standingsList = new StandingsList();
        
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createNewStandingsField = new javax.swing.JTextField();
        selectStandingsButton = new javax.swing.JButton();
        createStandingsButton = new javax.swing.JButton();

        jLabel1.setText("Select a standing from a list or create a new one");

        createNewStandingsField.setText("");

        selectStandingsButton.setText("Select");

        createStandingsButton.setText("Create");
        createStandingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStandingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createNewStandingsField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(createStandingsButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectStandingsButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createNewStandingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createStandingsButton)
                .addGap(106, 106, 106)
                .addComponent(selectStandingsButton)
                .addGap(0, 92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createStandingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStandingsButtonActionPerformed
       this.standings = new Standings(createNewStandingsField.getText());
       this.textField = this.standings.getName();
      
    }//GEN-LAST:event_createStandingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField createNewStandingsField;
    private javax.swing.JButton createStandingsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selectStandingsButton;
    // End of variables declaration//GEN-END:variables
}
